/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add-slide`; params?: Router.UnknownInputParams; } | { pathname: `/control`; params?: Router.UnknownInputParams; } | { pathname: `/create-qr`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/presentation`; params?: Router.UnknownInputParams; } | { pathname: `/tv`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/qr-view/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/slide-view/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/add-slide`; params?: Router.UnknownOutputParams; } | { pathname: `/control`; params?: Router.UnknownOutputParams; } | { pathname: `/create-qr`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/presentation`; params?: Router.UnknownOutputParams; } | { pathname: `/tv`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/qr-view/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/slide-view/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/add-slide${`?${string}` | `#${string}` | ''}` | `/control${`?${string}` | `#${string}` | ''}` | `/create-qr${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/presentation${`?${string}` | `#${string}` | ''}` | `/tv${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add-slide`; params?: Router.UnknownInputParams; } | { pathname: `/control`; params?: Router.UnknownInputParams; } | { pathname: `/create-qr`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/presentation`; params?: Router.UnknownInputParams; } | { pathname: `/tv`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | `/qr-view/${Router.SingleRoutePart<T>}` | `/slide-view/${Router.SingleRoutePart<T>}` | { pathname: `/qr-view/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/slide-view/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
